SimpleBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls"))
]

blog/urls.py
from django.urls import path
from . import views

app_name="blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("article/search/", views.search, name="search"),
    path("register/", views.sign_in, name="register"),
    path("login/", views.login, name="login"),
    path("article/<str:str>/", views.show_post, name="show_post")
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}SimpleBlog - So Simple{% endblock %}</title>
        <link rel="icon" href="{% static "SimpleBlog.png" %}" type="image/png" sizes="64x64">
        <link rel="stylesheet" type="text/css" href="{% static "base/base.css" %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    </head>

    <body>
        <nav class=" navbar navbar-expand-lg navbar-light bg-light mb-3">
            <div class="container" id="navbar-quirks">
                <div class="justify-content-start">
                    <a class="navbar-brand mr-1" href="{% url "blog:index" %}">SimpleBlog </a>
                    <span class="small note align-bottom">So Simple<span>
                </div>
                <div class="justify-content-end">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>

                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url "blog:search" %}">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search for posts" aria-label="Search" id="header" name="header">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>

        
        {% block content %}
        <main class="d-flex flex-column container">
            {% for post in posts %}
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{post.header|upper}}</h5>
                        <p class="card-text small">{{post.sub_header|upper}}</p>
                        <p class="card-text small">Published at {{post.pub_date|date:"d/m/Y"}}</p>
                        <p class="card-text small">Author: {{post.author.first_name|capfirst}} {{post.author.last_name|capfirst}}</p>
                        <a href="{% url "blog:show_post" post.header %}" class="btn btn-primary">Read More</a>
                    </div>
                </div>
            {% empty %}
                <div class="d-flex justify-content-center align-items-center h-100">
                    <h2>No post was found :(</h2>
                </div>
            {% endfor %}
        </main>

        {% if posts.paginator.num_pages > 1 %}
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if posts.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="{{request.path}}?page={{posts.previous_page_number}}{{header}}" tabindex="-1">Previous</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="{{request.path}}?page={{posts.previous_page_number}}{{header}}">{{posts.previous_page_number}}</a></li>
                {% endif %}

                <li class="page-item active"><a class="page-link">{{posts.number}}</a></li>
                {% if posts.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{{request.path}}?page={{posts.next_page_number}}{{header}}">{{posts.next_page_number}}</a></li>
                <li class="page-item">
                    <a class="page-link" href="{{request.path}}?page={{posts.next_page_number}}{{header}}">Next</a>
                </li>
                {% endif %}
            </ul>
    
        </nav>
        {% endif %}
        {% endblock %}

        <footer class="bg-dark mt-3">
            <div class="container h-100">
                <div class="d-flex justify-content-center align-items-center text-white h-100">
                    <span>Seek the simplicity&#8482;</span>
                </div>
            </div>
        </footer>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        {% block footer %}
        {% endblock %}
    </body>

</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}{{post.header}}{% endblock %}

{% block content%}
<main class="d-flex flex-column container">
    <div class="mb-3">
        <h2>{{post.header|upper}}</h2>
        <h6 class="text-muted">{{post.sub_header|upper}}</h6>
    </div>

    <div class="text-justify">
        <p>{{post.content|safe}}</p>
    </div>

    <div class="mt-2 mb-5">
        <p class="small">Published at {{post.pub_date|date:"d/m/Y"}}</p>
        <p class="small">Author: {{post.author.first_name|capfirst}} {{post.author.last_name|capfirst}}</p>
    </div>
</main>
<div class="container">
    <div class="mb-5">
        <form method="POST" class="mb-3" id="commentForm">
            {# Not sure if name should be given hard-coded... #}
            <input type="number" hidden="" id="{{comment_form.reply.auto_id}}" name="reply">
            {% csrf_token %}
            <div class="form-group">
                {% if comment_form.author.errors %}
                    <p>
                        You are not logged. Have an account? click on login otherwise click on register for such.
                    </p>
                    <div class="ml-auto mb-5">
                        <a href="{% url "blog:login" %}?redirect={{request.path|urlencode}}" class="btn btn-primary">Login</a>
                        <a href="{% url "blog:register" %}?redirect={{request.path|urlencode}}" class="btn btn-secondary">Register</a>
                    </div>
                {% endif %}
                {% if comment_form.reply.errors %}
                <p>
                    It was not possible to reply to a comment.
                </p>
                {% endif %}
                <label for="{{ comment_form.content.auto_id }}" id="{{ comment_form.content.auto_id }}_label">{{comment_form.content.label}}</label>
                {{comment_form.content}}
            </div>
            <div class="d-inline-flex" id="commentButtons">
                <button type="submit" class="btn btn-primary">Send comment</button>
            </div>
        </form>
    </div>
    <h4>Comments:</h4>
    {% for comment in comments %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{comment.author}}{% if comment.reply %} - Replied to {{ comment.reply.author }}{% endif %}</h5>
                {% if comment.reply %}
                <div class="bg-light border mb-3">
                    <p class="card-text">{{comment.reply.content}}</p>
                </div>
                {% endif %}
                <p class="card-text">{{comment.content}}</p>
                <p class="card-text">Commented at {{comment.comment_date|date:"d/m/Y H:i"}}</p>
                <a class="card-link" onClick="transcriptReply('{{ comment.author }}', '{{ comment.content|truncatechars:80|escapejs }}', {{comment.id}})">Reply</a>
            </div>
        </div>
    {% empty %}
        <div class="d-flex justify-content-center mt-5 mb-3">
            <p>No one commented on this post yet</p>
        </div>
    {% endfor %}
</div>
{% endblock %}
{% block footer %}
{% spaceless %}
<script>
    const replyMessage = "Send Reply"
    const nonReplyMessage = "Send Comment"

    function transcriptReply(author, content, id) {
        // Check if there's already a repply.
        if (document.getElementById("replyContent")) {
            removeRepply()
        }

        campValue = document.getElementById("{{ comment_form.reply.auto_id }}").setAttribute("value", id)
        campMessageLabel = document.getElementById("{{ comment_form.content.auto_id }}_label")
        campMessageLabel.hidden = true

        commentContent = document.createElement("template")
        commentContent.innerHTML = '<div id="replyContent"><h4>Replying to ' + author + '</h4> <p>Comment:' + content.toString() + 
                                   '</p></div>'
        commentContent = commentContent.content.firstChild

        commentForm = document.getElementById("commentForm")
        commentForm.insertBefore(commentContent, commentForm.childNodes[0])

        // Avoid having a hash on the url, it annoying when there's a need to
        // refresh the page.
        commentForm.scrollIntoView()

        commentButton = document.createElement("template")
        commentButton.innerHTML = '<button type="button" class="btn btn-secondary ml-3" onClick="removeRepply()" id="cancelRepplyButton">Cancel Reply</button>'
        commentButton = commentButton.content.firstElementChild

        // Buttons menu for comments
        commentButtons = document.getElementById("commentButtons")
        commentButtons.firstElementChild.innerHTML = replyMessage
        commentButtons.appendChild(commentButton)
    }

    function removeRepply () {
        // Remove comment reply header and comment message
        commentContent = document.getElementById("replyContent")
        commentContent.remove()

        // Remove cancel reply button        
        commentButton = document.getElementById("cancelRepplyButton")
        commentButton.remove()

        // Change send button text
        sendButton = document.getElementById("commentButtons").firstElementChild
        sendButton.innerHTML = nonReplyMessage
        
        // Unhide the label message
        campMessageLabel = document.getElementById("{{ comment_form.content.auto_id }}_label")
        campMessageLabel.hidden = false

        // Remove the attribute value from the form
        document.getElementById("{{ comment_form.reply.auto_id }}").removeAttribute("value")
    }
</script>
{% endspaceless %}
{% endblock %}

templates/error.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block content %}
<main class="d-flex flex-column container">
    <div class="d-flex justify-content-center align-items-center h-100">
        <h4>{{message}}</h4>
    </div>
</main>
{% endblock%}

templates/login.html
{% extends "base.html" %}

{% block title%}Login{% endblock %}

{% block content %}
<main class="d-flex flex-column container align">
    <div class="d-flex align-items-center justify-content-center h-100">
        <div class="p-5 shadow border border-dark w-100">
            <form method="POST">
                {% csrf_token %}
                {% for field_error in form.errors.values %}
                    <div class="text-danger">{{field_error}}</div>
                {% endfor %}
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.auto_id }}"> {{field.label}}</label>
                    {{field}}
                </div>
                {% endfor %}
                <input type="text" name="redirect" value="{{url_redirect}}" id="redirect" hidden="">
                <button type="submit" class="btn btn-primary"> Login </button>
            </form>
        </div>
    </div>
</main>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title%}Register{% endblock %}

{% block content %}
<main class="d-flex flex-column container">
    <div class="d-flex align-items-center justify-content-center h-100">
        <div class="p-5 shadow border border-dark w-100">
            {% for error in form.errors.values %}
                <div class="text-danger">{{error}}</div>
            {% endfor %}
            <form method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.auto_id }}">{{field.label}}</label>
                        {{field}}
                        <small class="form-text text-muted">{{field.help_text}}</small>
                    </div>
                {% endfor %}
                <input type="text" id="redirect" name="redirect" value="{{url_redirect}}" hidden="">
                <button type="submit" class="btn btn-primary"> Register </button>
            </form>
        </div>
    </div>
</main>
{% endblock %}